name: Tests

on:
  push:
    branches: [ main, 'release**' ]
  pull_request:
    branches: [ main, 'release**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Create tests infrastructure
        run: docker-compose -f docker-compose.tests.yml up -d

      - name: Run tests
        run: dotnet test ./tests/Notidar.Mongo2Elastic.Tests/Notidar.Mongo2Elastic.Tests.csproj"

      - name: Destroy tests infrastructure
        run: docker-compose -f docker-compose.tests.yml down